# Generated by Django 4.2.8 on 2024-07-14 14:08

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_book_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file_path',
            field=models.FileField(upload_to=main.models.audio_file_path),
        ),
    ]
